spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: porvanivafoo@gmail.com
    password: zgwb fusm vbzo ajdv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: Internship
  datasource:
    url: jdbc:postgresql://212.132.97.24:5432/pmokhammad
    username: pmokhammad
    password: qfP94j9woo8dISPS
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
